apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: wardex
  labels:
    app.kubernetes.io/name: wardex
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wardex
